[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.24"
optimizer = true
optimizer_runs = 20000
evm_version = "paris"

fs_permissions = [
  { access = "read-write", path = "./" },
  { access = "read", path = "./out" },
  { access = "read", path = "./lib" }
]

gas_reports = ["*"]

remappings = [
  "@uniswap/v4-core/=lib/v4-core/",
  "v4-core/=lib/v4-core/src/",
  "v4-periphery/=lib/v4-periphery/src/",
  "solmate/=lib/solmate/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]


# ✅ Fuzzing (default profile)
[fuzz]
runs = 256

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

# ✅ CI profile override
[profile.ci.fuzz]
runs = 1024
